### PR TITLE
AEROGEAR-3486 -  add and configure lint

### PR DESCRIPTION
**Pull request by ciaranRoche**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-3486

## Description

Currently, we do not enforce any code consistency rules.

## Progress

- [x] Add tslint
- [x] Add lint scripts
- [x] Add tslint.json
- [x] Configure tslint rules
- [x] Add to circle ci
- [x] Enforce rules on code base

## Additional Info
Due to the number of file changes, the important changes for review can be viewed at [d7bbfc4](https://github.com/aerogear/cordova-showcase-template/pull/88/commits/d7bbfc46594f8efe944354609acb938977fc5589). And to be more specific look at [tslint.json](https://github.com/ciaranRoche/cordova-showcase-template/blob/61780fc71d8cf212806d1e1af9df647e002538ae/tslint.json)

## Note
tslint does not enforce/fix indentation ([reference](https://palantir.github.io/tslint/rules/indent/)) so because of this we have used [a ts lint formatter](https://www.npmjs.com/package/typescript-formatter) that uses the tslint config and enforces and fixes indentation

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@ciaranRoche on it now

**Comment by aidenkeating** [comment]
:eyes:

**Comment by pawelpaszki** [comment]
@ciaranRoche html templates might need to be looked after as well as they have inconsistent formatting too, e.g. auth.html and authDetails.html

**Comment by ciaranRoche** [comment]
@pawelpaszki  considering the new goals, I think this PR is sufficient for now as it follows the same linting structure as our sdk, we can revisit looking at html or revising the linting rules in the future. What do you think?

**Comment by aidenkeating** [comment]
@pawelpaszki @ciaranRoche Let's revisit other linting areas in separate PRs, this PR is quite large as it is and other concerns take priority.

@ciaranRoche Verifying now

**Comment by pawelpaszki** [comment]
@ciaranRoche @aidenkeating agree to revisiting the other linting concerns. Other than that - excellent work. Checked all of the .ts files and they look consistent now. Also run the app with and without the services being configured. Seems to be working as expected

**Pull request merged**
