### PR TITLE
AEROGEAR-3564 - use #nochrome link to hide navbar on docs

### PR DESCRIPTION
**Pull request by jasonmadigan**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-3564

See also: https://github.com/aerogear/antora-ui/pull/13

### CODE REVIEW

**Comment by jasonmadigan** [comment]
```
ERROR: src/services/documentation.service.ts[10, 1]: Exceeds maximum line length of 120
ERROR: src/services/documentation.service.ts[12, 1]: Exceeds maximum line length of 120
```

Arghghgh

**Comment by wtrocki** [comment]
@jasonmadigan This is going to happen a lot with URL's and templates. 
It looks like we do not explicitly specify that so if we add:

`"max-line-length": [true, 140]`

to ts-config it will resolve problem for everyone.

More info: https://palantir.github.io/tslint/rules/max-line-length/

**Comment by ciaranRoche** [comment]
I have not been able to verify this on android :thinking: I am wondering am I missing a step, what menu are we trying to remove?

**Comment by jasonmadigan** [comment]
thanks @wtrocki - will add

@ciaranRoche should be able to verify this in a bit - I'm going to get https://github.com/aerogear/antora-ui/pull/11 merged - you'll be able to verify then

**Comment by jasonmadigan** [comment]
@laurafitzgerald @aidenkeating changes enabling this to be tested in aerogear/antora-ui#13 have been landed. Should be OK to do a quick test now?

**Comment by laurafitzgerald** [comment]
@ciaranRoche the tags are added in the redirect page. It's linked above. I'll go ahead and get that merged and published so we can get this moving.

**Comment by ciaranRoche** [comment]
@laurafitzgerald no problem, thanks for clarifying

**Comment by ciaranRoche** [comment]
@laurafitzgerald  @jasonmadigan Re-verifying the PR after the redirects where merged and it looks like we can not navigate to `#sso` on the redirect link, it looks to be the `header=false` :thinking:

**Comment by laurafitzgerald** [comment]
@ciaranRoche I pushed a [change](https://github.com/aerogear/docs.aerogear.org/pull/39) to fix it. Would you mind checking again if it works now.

**Comment by laurafitzgerald** [comment]
thanks for the verification @ciaranRoche I'll go ahead and merge the change.

**Pull request merged**
