### PR TITLE
changed config

### PR DESCRIPTION
**Pull request by StephenCoady**
## Motivation

Hide core configuration exposure from the client and instead use a new method in the auth package of the sdk.

See linked PR: https://github.com/aerogear/aerogear-js-sdk/pull/74

### CODE REVIEW

**Comment by wtrocki** [comment]
@StephenCoady @wei-lee @TommyJ1994 Is certificate pinning an feature of SDK or it just showcased in example app?

**Comment by ciaranRoche** [comment]
@wtrocki it is just showcased in the example app, I think there is plans to make it a feature of the SDK down the road, this got ported over from the old template app

**Comment by wtrocki** [comment]
I got context offline from @StephenCoady. Happy to merge this change.

I will personally recommend to port this stuff to SDK first and then build showcase on top of the SDK. This way we going to avoid exposing temporary methods like getConfig etc.

**Comment by wtrocki** [comment]
Testing if master will be picked up.

**Comment by wtrocki** [comment]
YEAH IT WORKS!


However due to npm issues if we introduce new package to the JS SDK it's not going to be installed. To resolve this problem we can use yarn or something like this:
https://www.npmjs.com/package/npm-safe-install

Options?

**Pull request merged**
