### PR TITLE
Documented how to run in the browser

### PR DESCRIPTION
**Pull request by trepel**
## Motivation

Added information on how to run the app in the browser. It is the simplest option so why not to document it. It is much easier especially if you don't have Android Emulator or iOS dev environment installed.

### CODE REVIEW

**Comment by StephenCoady** [comment]
@trepel @ciaranRoche is right - some of our functionality might behave differently. We also do not test anything on the browser only device.

**Comment by wtrocki** [comment]
SDK support on web
- Core 👍 
- Push 🛑
- Auth 🛑 
- Metrics 🛑 
- Security 🛑 

To support web we will need separate showcase, however with the nature of the SDK's now they will not make much sense for the web anyway (apart from Auth)

**Comment by trepel** [comment]
Thank you for all your reply guys. I tried to install on Android emulator but I received certificate errors (same happened for real device, I was using self-signed certificates). So I tried in a browser. I was only interested in Auth (Keycloak) and that worked. I didn't try integration with other Mobile Services.

For a jump start the browser way (despite the limitation of only Core & Auth) might be nice to have. However, you apparently think there is too little value for the browser. I am perfectly ok with closing this one then. If no other support for browser appears here I will close this later today.

**Comment by ciaranRoche** [comment]
You need to push certificates from your local cluster to a device or emulator, the easiest way to do that for Android is if you run
```
oc get secret router-certs --template='{{index .data "tls.crt"}}' -n default  |  \
base64 --decode | sed -e '1,/^-----END RSA PRIVATE KEY-----$/ d'  > /tmp/localcluster.crt
```
Then use adb to push the cert to your device/emulator
```
adb push /tmp/localcluster.crt /sdcard/Download/localcluster.crt
```
Once that is done, go to your `Download` folder on the device and select the `localcluster.crt` file and install it, you might need to add a screen lock too, but once its installed you should have no certificate issues with the app.

**Comment by wtrocki** [comment]
Auth may work depending on how redirect URL is being configured. If it will be application schema then it will not work. Currently it's localhost, but in the future this could change.

**Comment by StephenCoady** [comment]
Was just going to say that for now auth will work because the showcase doesn't make use of any app schema. Once we implement SSO then the browser will no longer work for auth either.

**Comment by wtrocki** [comment]
Actually this PR becomes really valuable source of information. 
@trepel If there is something we can do here we can also move that to the list to have more wider coverage.

**Comment by trepel** [comment]
Hi guys, sorry it took me so long to get back to this. I created a post in AeroGear group, I hope it is roughly what you expected it to be, feel free to reply there if not.

Based on your comments I was able to run the app (with auth) in both emulator and browser. It didn't work on real device though. I suspect it is because of redirect url, I used localhost as described in [getting started guide](https://docs.aerogear.org/aerogear/latest/getting-started.html)). Any ideas what to do to make it work on real device ? When I click "Authenticate" it just redirects me back to that screen again.

**Comment by StephenCoady** [comment]
@trepel are you able to access your cluster from the device browser normally (through chrome or whatever)?

**Comment by trepel** [comment]
@StephenCoady hmm, I can reach the OCP console, but I am not able to reach keycloak realm URL (via chrome)

**Comment by StephenCoady** [comment]
@trepel are you on fedora or mac? this sounds like a firewall issue myself and @ciaranRoche hit last week. If you are on fedora, this might help: https://github.com/aerogear/mobile-docs/pull/279

**Comment by trepel** [comment]
thank you @StephenCoady , that made it accessible indeed. It works now real device now as well.

Just for the record, yes, I am running Fedora and
```firewall-cmd --add-port 80/tcp```
```firewall-cmd --add-port 443/tcp```
was indeed the solution.

**Comment by trepel** [comment]
Closing the PR now, thanks again to all of you for your time and effort.

**Pull request closed without merging**
