### PR TITLE
AEROGEAR-2961 update the nav sidebar

### PR DESCRIPTION
**Pull request by StephenCoady**
- [x] Add all components to nav list from https://issues.jboss.org/browse/AEROGEAR-2929 and update all icons for parent items
- [x] Add under construction page
- [x] Remove card from top of menu and replace with solid bar
- [x] fix colour scheme
- [x] screen titles changed to reflect page
- [x] Add links to documentation from appropriate nav items

screenshot 2018-06-12 11 12 55
screenshot 2018-06-12 11 13 10

### CODE REVIEW

**Comment by wei-lee** [comment]
@StephenCoady can you take a look at the ios showcase app and make sure the views are aligned. A few comments:

1. on the home view, the link should be in its own paragraph. Also perhaps reduce the gap a little bit between the icon and the text
2. for the under construction page, can we make the header title to be the title of the view, and add "under construction" text to the page instead.

**Comment by StephenCoady** [comment]
@wei-lee @ciaranRoche @aidenkeating could you guys take a look if you have some time

**Comment by StephenCoady** [comment]
screenshot 2018-06-12 16 15 54
screenshot 2018-06-12 16 15 42

**Comment by wtrocki** [comment]
Worth to test on real device/different emulators.

**Pull request merged**
