### PR TITLE
Redirect after login/logout

### PR DESCRIPTION
**Pull request by jhellar**
## Motivation

When user logs in or logs out, he stays on the same page. So it may seem nothing has happened.

## Description

With this change, user is redirected after login/logout to user detail/login page.

### CODE REVIEW

**Comment by jhellar** [comment]
ping @StephenCoady

**Comment by TommyJ1994** [comment]
Verified on Android Emulator - works fine.

@jhellar Maybe we can do 2 extra things along with this change:
* Remove the the authenticated alert from the home screen - https://github.com/aerogear/cordova-showcase-template/blob/af8cc0328d711cb05c0a889349847f21bbc290b9/src/pages/home/home.ts#L20-L34

* Remove the Identity Profile link from the sidebar menu - since when we click on the Authentication menu button, it will bring us to the user profile screen if we are already authenticated.

https://github.com/aerogear/cordova-showcase-template/blob/6f76454e911a84a6e8b40b2bfef3542211118138/src/app/app.component.ts#L27

Sound ok?

**Comment by jhellar** [comment]
@TommyJ1994 Yes, that sounds good. Will update the PR.

**Comment by wtrocki** [comment]
@jhellar

**Comment by wtrocki** [comment]
@jhellar Let's rebase this if possible with the current master.

**Comment by jhellar** [comment]
@wtrocki rebased. Should work now for both Android and iOS. In browser it behaves differently - it redirects to home page after login/logout.

**Pull request merged**
