### PR TITLE
Fix cordova auth for IOS and Android

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Resolve problems with missing wait for device ready.

### CODE REVIEW

**Comment by jhellar** [comment]
Works for me on both Android and iOS.

Should there be the addresses? Can we use `<allow-navigation href="*"/>` instead?

As Auth module initializes after cordova "deviceready" event, authentication no longer works for `npm run ionic:serve`.

**Comment by wtrocki** [comment]
@jhellar Awesome work. Thank you for helping me with 
@TommyJ1994 
> Yeah, I think the addresses there can be removed as the issue was server-side in incoming requests.

Yes. Committed in the rush. Going to remove it

> Regarding the deviceready trigger for auth, I think we can probably remove the init from the startup/bootstrap and instead just have it on the Authenticate Button 

I think this should be kinda canonical solution that encourage people to use lib the way is documented. If we do not init at the beginning would we get valid app token. For the cases when app is launched and you are actually logged in.
I may misunderstood the keycloak.js code but init seems to be crucial part to make everything work.

**Comment by wtrocki** [comment]
@TommyJ1994 - I would love to get info what whitelist was added. Curious if we should document that for local development using this template.

**Comment by TommyJ1994** [comment]
@wtrocki Actually I think this is ok about the init() placement.

I added `http://localhost:8080/*` to the web origins, `http://localhost/*` was here before, but does not seem to catch it on iOS, only on Android. I can sync up with @jhellar later and experiment more to see if there is a catch-all for all platforms, and if necessary create some docs to handle iOS individially.

**Comment by wtrocki** [comment]
@TommyJ1994 It feels like hostname (with port) should be a standard here.

**Pull request merged**
