### PR TITLE
Aerogear 2526 security checks

### PR DESCRIPTION
**Pull request by rachael-oregan**
## Motivation

Refactor the security checks to use the security module from the JS-SDK

## Description

Added security checks from the security module into the app

### CODE REVIEW

**Comment by wtrocki** [comment]
Note: this fixes build:
https://github.com/aerogear/cordova-showcase-template/pull/31

**Comment by wtrocki** [comment]
Rebase samba! Rebase is strongly recommended.

**Comment by wtrocki** [comment]
@rachael-oregan Let't remove last commits and merge https://github.com/aerogear/cordova-showcase-template/pull/33

Then I will verify all things together

**Comment by rachael-oregan** [comment]
@wtrocki removed the last commit 👍

**Comment by wtrocki** [comment]
Trying to verify that together with @josemigallas

**Pull request merged**
